codecov:
  branch: main
coverage:
  round: down
  precision: 2
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 90%
      - type: patch
        target: 100%
